name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.8.3-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{}' \
          "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
